### ISSUE TITLE
Occasionally overviewer does a full re-render?

### ISSUE THREAD

**Issue by timvisher** [overviewer/Minecraft-Overviewer#1241]
I've got overviewer set up in a docker container into which i share my server world. Usually, things seem to work as advertised and only the pieces of the world that have been updated have their tiles re-rendered but occasionally, I've noticed that the entire world will update.

What are the conditions under which this can happen and how can I prevent them? The full world is pretty expensive to render at this point and the vast majority of it doesn't change between runs.

**Comment by LeadMagnet** [comment]
As far as I am aware, OV looks at the region file meta info to see if the file has been updated.

There are many reasons that a "file update" (update to meta info) can be made outside of MC or OV normal operation. Some backup utilities will change this information set "has been backed up/archived" flags. There are RAID hardware/software controllers that do this as well. Also, moving the files will flag them as updated, even if the world isn't even loaded/running.

HTH

:)

**Comment by timvisher** [comment]
At the moment, I'm not pausing world saves during the OV run. Is it possible that an in-situ update while OV is running would trigger this sort of thing? I'm thinking about trying to get backups working and then only running OV based on backups. Do you think that sort of thing would reduce the noise?

**Comment by LeadMagnet** [comment]
It is very possible something on the server is causing this to happen, especially if you're running a Windows machine.

Running OV from backup could solve the issue, however the backup software might run into the same issue. Backup software also looks at meta info to determine if a file should be backed up or skipped. 

My setup, I use rsync to copy region files from the MC server to my mapping server (both VM's). Rsync does not modify meta info during a file transfer, so OV only renders what has indeed changed. This has worked very well over the past year. I never had the issue you are having, even with the MC server running CentOS and my mapping server running Windows Server 2012R2.

**Comment by CounterPillow** [comment]
On Linux/OSX, we use region file mtime and in-file chunk mtime to determine what needs to be rerendered; on Windows, we only use chunk mtime since Windows doesn't update a file's mtime until all file handles are closed from what we know.

In essence, this means you should make sure not to mess up file mtimes during copying, and you should make sure no server-side plugin modifies every chunk in the world for some inane reason.

**Comment by timvisher** [comment]
@CounterPillow The server is running inside a [Docker container](https://github.com/itzg/dockerfiles/tree/master/minecraft-server) which has a volume from an OS X host (HFS+ fs) mounted inside of it for world save data etc. The server is entirely vanilla with no mods or anything installed. Not sure what could be causing the chunk update.

Files are being directly shared into the OV container using docker volumes and thus persisted between runs. Again, the volume is from an OS X host.

So in this instance no copying is being done at all, afaik. But that said, does anything about the above set up strike you as something that would mess with mtimes?

Another strange datapoint, though I just witnessed a full re-render that consumed about 3 hours of compute times, `rsync -avzP` reported that only about 1000 files were changed (compared to the 50k or so that are actually there).

**Comment by CounterPillow** [comment]
is the time inside and outside the container properly synced?

**Comment by timvisher** [comment]
I'm almost certain they wouldn't be. VirtualBox has notoriously bad time problems, iiuc. At this point I'm not sure exactly what I'm winning by running it inside docker. I may drop it onto the host instead sometime soon or instead run it directly on a vm.

**Comment by timvisher** [comment]
So my interpretation of what was happening was faulty. OV was not doing full re-renders. Just large portion re-renders (roughly 1/3 of the total tiles).

I now have a 'reliable' (maybe? i hope?) backup system in place which does a simple `save-off save-all rsync -avzP $(date +%Y…) save-on` and i'm generating overviewer updates based on them.

What's interesting is that I can't get it to render less than 897 tiles between runs, and runs are happening continuously. No one is logged into the server, and like I said auto saves are being turned off during the run.

If I run OV continuously on a single directory (i.e. one of the backups) then I get 0 tiles updated between each one.

Is there anything I can do to diagnose what is being updated and why it's being updated?

**Comment by timvisher** [comment]
OK here's some good news. I turned off auto-saving entirely and just re-ran OV a couple of times. It works flawlessly. 0 tiles updated between each run.

So something's being updated by the server too regularly, I suppose?

**Comment by timvisher** [comment]
Sure enough, the moment I turn auto-saving back on, I get 897 tiles updated again.

**Comment by timvisher** [comment]
It also appears to bottom out at 897. I just ran it again after about 2 hours and I'm up to 4275.

**Comment by timvisher** [comment]
Doing some more diagnosis here.

I found that the region files are indeed being updated at a rate that I can't explain. `world/region/r.0.0.mca` seems to receive an update once every 30 seconds or so, as evidenced by the following:

```
root@ada41ad662ca:/data# for n in {1..10}; do stat -c '+%y' world/region/r.0.0.mca; sleep 30; done
+2015-07-08 18:06:01.000000000 +0000
+2015-07-08 18:06:01.000000000 +0000
+2015-07-08 18:06:57.000000000 +0000
+2015-07-08 18:07:31.000000000 +0000
+2015-07-08 18:07:31.000000000 +0000
+2015-07-08 18:08:27.000000000 +0000
+2015-07-08 18:09:01.000000000 +0000
+2015-07-08 18:09:01.000000000 +0000
+2015-07-08 18:09:57.000000000 +0000
+2015-07-08 18:10:31.000000000 +0000
root@ada41ad662ca:/data#
```

Other files are being updated too, like the villages.dat files. I'm assuming more of the regions get updated over time.

**Comment by timvisher** [comment]
Actually, the files that are being updated at that roughly 30 second interval are pretty consistently the following

```
world/level.dat
world/level.dat_old
world/data/villages.dat
world/data/villages_end.dat
world/data/villages_nether.dat
world/region/r.0.0.mca
```

If that sheds any light on anything.

**Comment by timvisher** [comment]
Another interesting point:

```
root@ada41ad662ca:/data# for n in {1..10}; do echo $(stat -c '+%y' world/region/r.0.0.mca) $(md5sum world/region/r.0.0.mca); sleep 30; done
+2015-07-08 18:24:09.000000000 +0000 a1c1c8622399bef02012b91d6c602b7b world/region/r.0.0.mca
+2015-07-08 18:24:09.000000000 +0000 a1c1c8622399bef02012b91d6c602b7b world/region/r.0.0.mca
+2015-07-08 18:24:57.000000000 +0000 05b3e616f5fc9943ba987f96d10a3bde world/region/r.0.0.mca
+2015-07-08 18:25:39.000000000 +0000 f7e83d7dfde3700cfe345068729733e7 world/region/r.0.0.mca
+2015-07-08 18:25:39.000000000 +0000 f7e83d7dfde3700cfe345068729733e7 world/region/r.0.0.mca
```

I don't believe the a/mtime is stored in the files bits themselves so the file is in fact being updated, it would seem.

**Comment by timvisher** [comment]
Ah! I think I just solved at least this mystery. I totally blanked on the fact the spawn chunks are always active. That makes perfect sense. I'm assuming that OV can't do anything more intelligent regarding them at least. Is it just that the chunk is loaded and thus is being updated that triggers the re-render or is it that the chunk was actually changed? Is there no way to tell the difference between the two?

**Comment by MasterofJOKers** [comment]
But isn't it also true, that the spawn chunks cannot be changed by users? Could OV just ignore the spawn chunks after rendering them once?

**Comment by CounterPillow** [comment]
they can still be changed by OPs, and block updates like grass growing or similar can probably still happen.

What we could do is hash all the relevant data of the spawn chunks and use that instead of the (unreliable) mtimes.

**Comment by timvisher** [comment]
@MasterofJOKers @CounterPillow I believe server admins can also disable spawn chunk protection. Hashing resulting tiles and comparing them with what's present would probably be the only reliable (if costly) approach.
