### ISSUE TITLE
ValueError: cannot reshape array of size 1024 into shape (16,16)

### ISSUE THREAD

**Issue by InSinU8** [overviewer/Minecraft-Overviewer#1721]
This is the error that occurred:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.6/dist-packages/overviewer_core/aux_files/genPOI.py", line 125, in parseBucketChunks
    data = rset.get_chunk(b[0], b[1])
  File "/usr/local/lib/python3.6/dist-packages/overviewer_core/world.py", line 1369, in get_chunk
    biomes = biomes.reshape((16,16))
ValueError: cannot reshape array of size 1024 into shape (16,16)
"""

Just getting this error, not sure what's going on.

**Comment by CounterPillow** [comment]
Update overviewer, this has been fixed months ago.

**Comment by InSinU8** [comment]
I'm still getting this issue with .15.2~overviewer1 .deb

Reading state information... Done
minecraft-overviewer is already the newest version (0.15.2-0~overviewer1).

**Comment by CounterPillow** [comment]
Run `overviewer.py --version`
